const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: "1100px",
    padding: "5px",
    gap: "8px",
    backgroundColor: "#000",
    color: "white",
  },
  containerDesktop: {
    flexDirection: "row",
  },
  panel1: {
    width: "100%",
    backgroundColor: "#1F2937",
    borderRadius: "8px",
    padding: "10px",
    height: "auto", // Changed from fixed height to auto
    minHeight: "400px", // Minimum height for mobile
    overflow: "hidden",
    marginBottom: "20px",
  },
  panel2: {
    width: "100%",
    backgroundColor: "#1F2937",
    borderRadius: "8px",
    padding: "10px",
    height: "auto", // Changed from fixed height to auto
    minHeight: "400px", // Minimum height for mobile
    overflow: "hidden", // Add scroll if content overflows
    marginBottom: "20px",
  },
  tabButton: {
    padding: "8px 16px",
    borderRadius: "4px",
    border: "none",
    backgroundColor: "transparent",
    color: "white",
    cursor: "pointer",
  },
  activeTabButton: {
    backgroundColor: "#374151",
  },
  flexRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "16px",
    padding: "2px",
    // width: "150px",
    fontSize: "12px",
  },
  flexBetween: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "12px",
  },
  gridHeader: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "16px",
    marginBottom: "8px",
    fontSize: "14px",
    color: "#9CA3AF",
  },
  gridRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "16px",
    padding: "4px 0",
  },
  orangeText: {
    color: "#F97316",
    fontSize: "12px",
  },
  greenText: {
    color: "#4ADE80",
    fontSize: "12px",
  },
  totalSection: {
    marginTop: "16px",
    paddingTop: "8px",
    borderTop: "1px solid #374151",
    display: "flex",
    justifyContent: "space-between",
    fontWeight: "500",
    fontSize: "12px",
  },
  greenRow: {
    backgroundColor: "rgba(16, 185, 129, 0.1)",
  },
  orderTypeButton: {
    padding: "8px 16px",
    border: "none",
    margin: "4px",
    backgroundColor: "transparent",
    color: "white",
    borderRadius: "4px",
    cursor: "pointer",
  },
  activeOrderTypeButton: {
    backgroundColor: "#374151",
  },
  inputContainer: {
    backgroundColor: "#374151",
    borderRadius: "4px",
    padding: "12px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  input: {
    backgroundColor: "transparent",
    border: "none",
    color: "white",
    textAlign: "right",
    width: "50px",
    outline: "none",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "center",
    marginBottom: "16px",
  },
  checkbox: {
    width: "20px",
    height: "20px",
    borderRadius: "4px",
    backgroundColor: "#3B82F6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "8px",
  },
  buyButton: {
    width: "100%",
    padding: "12px",
    borderRadius: "4px",
    border: "none",
    background:
      "linear-gradient(90deg, #483BEB 0%, #7847E1 47.92%, #DD568D 96.35%)",
    color: "white",
    fontWeight: "500",
    cursor: "pointer",
    marginBottom: "16px",
  },
  depositButton: {
    padding: "8px 32px",
    borderRadius: "4px",
    border: "none",
    backgroundColor: "#3B82F6",
    color: "white",
    fontWeight: "500",
    cursor: "pointer",
    marginTop: "16px",
  },
  infoIcon: {
    width: "16px",
    height: "16px",
    marginLeft: "4px",
    opacity: "0.7",
  },
  dropdown: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
  },
  dropdownIcon: {
    width: "16px",
    height: "16px",
    marginLeft: "4px",
  },
  gridContainer: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
    marginTop: "16px",
  },
  label: {
    fontSize: "14px",
    color: "#9CA3AF",
  },
  orderTypeDropdown: {
    position: "relative",
    fontSize: "12px",
  },
  dropdownMenu: {
    position: "absolute",
    top: "100%",
    right: "0",
    backgroundColor: "#374151",
    borderRadius: "4px",
    padding: "8px 0",
    zIndex: "10",
    width: "200px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  dropdownItem: {
    padding: "8px 16px",
    cursor: "pointer",
  },
  dropdownItemHover: {
    backgroundColor: "#4B5563",
  },
  sellButton: {
    padding: "8px 24px",
    borderRadius: "4px",
    border: "1px solid #EF4444",
    backgroundColor: "transparent",
    color: "white",
    cursor: "pointer",
  },
  buyTabButton: {
    padding: "8px 24px",
    borderRadius: "4px",
    border: "none",
    backgroundColor: "transparent",
    color: "white",
    cursor: "pointer",
  },
  orderTypeSelector: {
    display: "flex",
    marginBottom: "16px",
    fontSize: "12px",
  },
  orderTypeSelectorLeft: {
    borderTopLeftRadius: "4px",
    borderBottomLeftRadius: "4px",
  },
  orderTypeSelectorRight: {
    borderTopRightRadius: "8px",

    borderBottomRightRadius: "4px",
  },
};

export default styles;
